- hosts: all
  become: true
  tasks:
  #traffic configuration
  - name: Configure br_netfilter in modules for K8S
    ansible.builtin.copy:
      src: modules-k8s.conf
      dest: /etc/modules-load.d/k8s.conf
      owner: root
      group: root
      mode: u=rw,g=rw

  - name: Configure br_netfilter in sysctl for K8S
    ansible.builtin.copy:
      src: sysctl-k8s.conf
      dest: /etc/sysctl.d/k8s.conf
      owner: root
      group: root
      mode: u=rw,g=rw
  
  - name: Load all settings from all system config files
    command: "sysctl --system"

  #K8s preparation
  - name: Install Pre Kubernetes packages
    ansible.builtin.apt: name={{ item }} state=present
    with_items:
      - ca-certificates
      - apt-transport-https
      - curl

  - name: Add Google's official GPG key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Add K8s repository
    apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    
  - name: Install Kubelet, Kubeadm and Kubectl
    ansible.builtin.apt: name={{item}} state=present
    with_items:
      - kubelet
      - kubeadm
      - kubectl

  - name: Pin Kubelet version
    dpkg_selections:
      name: kubelet
      selection: hold

  - name: Pin Kubeadm version
    dpkg_selections:
      name: kubeadm
      selection: hold

  - name: Pin Kubectl version
    dpkg_selections:
      name: kubectl
      selection: hold
  
  #Container engine configuration
  - name: Install Pre Docker packages
    ansible.builtin.apt: name={{ item }} state=present
    with_items:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

  - name: Add Docker's official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker repository
    apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    
  - name: Install Docker & Docker Compose
    ansible.builtin.apt: name={{item}} state=present
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

  - name: Creating docker config file
    ansible.builtin.file:
      path: "/etc/docker"
      state: directory
  
  - name: Copying docker config file template to nodes
    ansible.builtin.copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: u=rw,g=rw

  - name: Restart Docker
    ansible.builtin.service:
      name: docker
      enabled: yes
  
  - name:
    ansible.builtin.service:
      name: docker
      state: restarted
      daemon_reload: yes
